[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/netlify/functions/json-server"
  status = 200

[dev]
  publish = "public/"
  functions = "functions/"
